repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0  # frozen: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: trailing-whitespace
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        args:
          - --no-ensure-ascii
          - --no-sort-keys
          - --indent
          - '2'
          - --autofix
      # check for file bigger than 500kb
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/timothycrosley/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/myint/autoflake
    rev: 862cc98ee47b27951f7cb4cf7aee8fcec657faab  # frozen: v1.5.3
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/psf/black
    rev: 2018e667a6a36ee3fbfa8041cd36512f92f60d49  # frozen: 22.8.0
    hooks:
      - id: black
