repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: trailing-whitespace
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        args:
          - --no-ensure-ascii
          - --no-sort-keys
          - --indent
          - '2'
          - --autofix
      # check for file bigger than 500kb
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort

  - repo: https://github.com/Trim21/mirrors-autoflake
    rev: ''
    hooks:
      - id: autoflake
        args: ['--in-place',
               '--remove-unused-variables',
               '--remove-all-unused-imports']
        require_serial: true

  - repo: local
    hooks:
      - id: yapf
        name: yapf
        entry: yapf -i
        require_serial: true
        language: system
        types: [python]
